version: '3'
services:
  flextesa:
    restart: always
    image: "pyratzlabs/tezos:ithaca"
    expose:
      - 8732/tcp
    ports:
      - 0.0.0.0:8732:8732

  dex:
    image: "bakingbad/pytezos"
    command: tail -F /dev/null
    volumes:
      - .:/contracts
    links:
      - flextesa

