#if !DEX_ERRORS
#define DEX_ERRORS


[@inline]
let error_SELF_IS_UPDATING_TOKEN_POOL_MUST_BE_FALSE  =
  201n


[@inline]
let error_THE_CURRENT_TIME_MUST_BE_LESS_THAN_THE_DEADLINE  =
  202n


[@inline]
let error_MAX_TOKENS_DEPOSITED_MUST_BE_GREATER_THAN_OR_EQUAL_TO_TOKENS_DEPOSITED  =
  203n


[@inline]
let error_LQT_MINTED_MUST_BE_GREATER_THAN_MIN_LQT_MINTED  =
  204n


[@inline]
let error_LQT_CONTRACT_MUST_HAVE_A_MINT_OR_BURN_ENTRYPOINT  =
  205n


[@inline]
let error_THE_AMOUNT_OF_TOKENS_WITHDRAWN_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MIN_TOKENS_WITHDRAWN  =
  206n


[@inline]
let error_CANNOT_BURN_MORE_THAN_THE_TOTAL_AMOUNT_OF_LQT  =
  207n


[@inline]
let error_TOKEN_POOL_MINUS_TOKENS_WITHDRAWN_IS_NEGATIVE  =
  208n


[@inline]
let error_TOKENS_BOUGHT_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MIN_TOKENS_BOUGHT  =
  209n


[@inline]
let error_TOKEN_POOL_MINUS_TOKENS_BOUGHT_IS_NEGATIVE  =
  210n


[@inline]
let error_ONLY_MANAGER_CAN_SET_MANAGER  =
  211n


[@inline]
let error_LQT_ADDRESS_ALREADY_SET  =
  212n


[@inline]
let error_INVALID_FA12_TOKEN_CONTRACT_MISSING_GETBALANCE  =
  213n


[@inline]
let error_INVALID_FA2_TOKEN_CONTRACT_MISSING_BALANCE_OF  =
  214n


[@inline]
let error_THIS_ENTRYPOINT_MAY_ONLY_BE_CALLED_BY_GETBALANCE_OF_TOKENADDRESS  =
  215n


[@inline]
let error_INVALID_FA2_BALANCE_RESPONSE  =
  216n


[@inline]
let error_LQT_ADDRESS_IS_NOT_SET  =
  217n


[@inline]
let error_K2_SHOULD_BE_GREATER_THAN_K1  =
  218n


[@inline]
let error_A_PROTOCOL_FEE_IS_TOO_BIG  =
  219n


[@inline]
let error_B_PROTOCOL_FEE_IS_TOO_BIG  =
  220n


[@inline]
let error_NON_EXISTING_ENTRYPOINT2  =
  221n


[@inline]
let error_NON_EXISTING_ENTRYPOINT12  =
  222n


[@inline]
let error_UPDATETOKENENDED_NOT_FOUND_IN_SELF  =
  223

#endif