[@inline] let error_THIS_ENTRYPOINT_DOES_NOT_ACCEPT_XTZ = 200n
[@inline] let error_SELF_IS_UPDATING_TOKEN_POOL = 201n
[@inline] let error_ADD_LIQUIDITY_DEADLINE_IS_OVER = 202n
[@inline] let error_MAX_TOKENS_DEPOSITED_MUST_BE_GREATER_THAN_OR_EQUAL_TO_TOKENS_DEPOSITED = 203n
[@inline] let error_LQT_MINTED_MUST_BE_GREATER_THAN_MIN_LQT_MINTED = 204n
[@inline] let error_FA12_CONTRACT_MUST_HAVE_A_TRANSFER_ENTRYPOINT = 205n
[@inline] let error_FA2_CONTRACT_MUST_HAVE_A_TRANSFER_ENTRYPOINT = 206n
[@inline] let error_NO_UNIT_CONTRACT = 207n
[@inline] let error_LQT_ADDRESS_IS_NOT_SET = 208n
[@inline] let error_LQT_CONTRACT_MUST_HAVE_A_MINT_OR_BURN_ENTRYPOINT = 209n
[@inline] let error_REMOVE_LIQUIDITY_DEADLINE_IS_OVER = 210n
[@inline] let error_THE_AMOUNT_OF_TOKEN_A_WITHDRAWN_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MIN_TOKENS_WITHDRAWN = 211n
[@inline] let error_CANNOT_BURN_MORE_THAN_THE_TOTAL_AMOUNT_OF_LQT = 212n
[@inline] let error_TOKEN_POOL_MINUS_TOKENS_WITHDRAWN_IS_NEGATIVE = 213n
[@inline] let error_SWAP_DEADLINE_IS_OVER = 214n
[@inline] let error_TOKENS_BOUGHT_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MIN_TOKENS_BOUGHT = 215n
[@inline] let error_TOKEN_POOL_MINUS_TOKENS_BOUGHT_IS_NEGATIVE = 216n
[@inline] let error_INCORRECT_XTZ_AMOUNT_WAS_SENT = 217n
[@inline] let error_BALANCE_OF_VIEW_RETURNED_AN_ERROR = 218n
[@inline] let error_THE_AMOUNT_OF_TOKEN_B_WITHDRAWN_MUST_BE_GREATER_THAN_OR_EQUAL_TO_MIN_TOKENS_WITHDRAWN = 219n
[@inline] let error_ONLY_MANAGER_CAN_SET_LIQUIDITY_ADDRESS = 220n
[@inline] let error_NO_TOKENS_WERE_BOUGHT = 221n
[@inline] let error_NON_EXISTING_ENTRYPOINT2 = 222n
[@inline] let error_NON_EXISTING_ENTRYPOINT12 = 223n
[@inline] let error_INVALID_FA2_TOKEN_CONTRACT_MISSING_BALANCE_OF = 224n
[@inline] let error_INVALID_FA12_TOKEN_CONTRACT_MISSING_GETBALANCE = 225n
[@inline] let error_INVALID_FA2_BALANCE_RESPONSE = 226n
[@inline] let error_UPDATETOKENENDED_NOT_FOUND_IN_SELF = 227n
[@inline] let error_CALL_NOT_FROM_AN_IMPLICIT_ACCOUNT = 228n
[@inline] let error_SELF_IS_UPDATING_TOKEN_POOL_MUST_BE_FALSE = 229n
[@inline] let error_THIS_ENTRYPOINT_MAY_ONLY_BE_CALLED_BY_GETBALANCE_OF_TOKENADDRESS = 230n
[@inline] let error_NO_AMOUNT_TO_BE_SENT = 231n
[@inline] let error_ONLY_MANAGER_CAN_UPDATE_SINK_ADDRESS = 232n
[@inline] let error_ONLY_MANAGER_CAN_SET_BAKER = 233n
[@inline] let error_BAKER_PERMANENTLY_FROZEN = 234n
(* 235n *)
(* 236n *)
(* 237n *)
[@inline] let error_AMOUNT_MUST_BE_SENT = 238n
[@inline] let error_NO_SINK_DEPOSIT_ENTRYPOINT_EXISTS = 239n
(* 240n *)
(* 241n *)
(* 242n *)
(* 243n *)
(* 244n *)
(* 245n *)
(* 246n *)
(* 247n *)
(* 248n *)
[@inline] let error_USER_BALANCE_IS_INSUFFICIENT = 249n
[@inline] let error_REWARD_LARGER_THAN_BALANCE = 250n
[@inline] let error_NO_REWARDS_FOR_THIS_PAIR = 251n

